spring.application.name=GPA_Calculator
spring.datasource.url=jdbc:postgresql://localhost:5432/gpa
spring.datasource.username=postgres
spring.datasource.password=26122003
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=9f2c0a7e4b1d8c3a6e5f0d2c9b7a1e4f8d6c3b2a9e0f1d7c5b4a3d2e1f0c9b8a
app.jwt.expiration-ms=86400000